.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. gamcoin_qt test_gamcoin_qt
clean: FORCE
	$(MAKE) -C .. gamcoin_qt_clean test_gamcoin_qt_clean
check: FORCE
	$(MAKE) -C .. test_gamcoin_qt_check
gamcoin-qt gamcoin-qt.exe: FORCE
	 $(MAKE) -C .. gamcoin_qt
apk: FORCE
	$(MAKE) -C .. gamcoin_qt_apk
